const dotenv = require('dotenv');
const connectDB = require('../config/db');
const Product = require('../models/Product');
const Category = require('../models/Category');

dotenv.config();

const categories = [
  { name: 'Chargers & Cables', slug: 'chargers-cables', description: 'Phone chargers, USB cables, power adapters and charging accessories.' },
  { name: 'Power Banks', slug: 'power-banks', description: 'Portable power banks and battery packs for on-the-go charging.' },
  { name: 'Headphones & Audio', slug: 'headphones-audio', description: 'Wireless headphones, earbuds, speakers and audio accessories.' },
  { name: 'Keyboards', slug: 'keyboards', description: 'Mechanical, membrane and wireless keyboards for work and gaming.' },
  { name: 'Gaming Accessories', slug: 'gaming-accessories', description: 'Gaming mice, controllers, headsets, pads and more.' },
  { name: 'Smart Watches', slug: 'smart-watches', description: 'Smartwatches and fitness trackers with health monitoring features.' },
  { name: 'PC Accessories', slug: 'pc-accessories', description: 'Monitors, webcams, USB hubs, cooling pads and desk accessories.' },
  { name: 'Networking', slug: 'networking', description: 'Wi-Fi routers, mesh systems, switches and network adapters.' },
];

const sampleProducts = [
  // ─── Chargers & Cables ─────────────────────────────────────────────────────
  {
    name: 'Anker 735 Charger GaNPrime 65W',
    description: 'Ultra-compact 65W GaN charger with 3 ports (2× USB-C + 1× USB-A). Charges a MacBook Pro, iPhone and AirPods simultaneously. ActiveShield 2.0 monitors temperature 3 million times per day.',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    category: 'Chargers & Cables',
    brand: 'Anker',
    countInStock: 120,
    rating: 4.8,
    numReviews: 2847,
    isFeatured: true,
  },
  {
    name: 'Apple 140W USB-C Power Adapter',
    description: 'Apple\'s most powerful USB-C charger supports MagSafe 3 fast-charging for MacBook Pro. Compact design with foldable prongs. Compatible with all USB-C devices.',
    price: 79.00,
    image: 'https://images.unsplash.com/photo-1601524909162-ae8725290836?w=800&q=80',
    category: 'Chargers & Cables',
    brand: 'Apple',
    countInStock: 65,
    rating: 4.6,
    numReviews: 1120,
    isFeatured: false,
  },
  {
    name: 'Belkin 200W USB-C 6-Port Desktop Charger',
    description: '200W desktop charging station with 6 ports including 4× USB-C and 2× USB-A. Ideal for families and multi-device users. Intelligent power distribution ensures each device gets the wattage it needs.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1563884072595-64c87e1a8f50?w=800&q=80',
    category: 'Chargers & Cables',
    brand: 'Belkin',
    countInStock: 44,
    rating: 4.5,
    numReviews: 674,
    isFeatured: false,
  },
  {
    name: 'Cable Matters Braided USB4 Cable 240W',
    description: '3ft USB4 Gen 3 cable delivering 40Gbps data, 8K video and 240W charging in one cable. Thunderbolt 4 compatible. Reinforced braided nylon jacket rated for 20,000 bends.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    category: 'Chargers & Cables',
    brand: 'Cable Matters',
    countInStock: 200,
    rating: 4.7,
    numReviews: 983,
    isFeatured: false,
  },

  // ─── Power Banks ────────────────────────────────────────────────────────────
  {
    name: 'Anker 24,000mAh Power Bank 65W',
    description: 'Massive 24,000mAh capacity with 65W USB-C output — enough to fully charge a MacBook Air twice. Built-in LED indicator, foldable prongs for direct wall charging, and 3 output ports.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&q=80',
    category: 'Power Banks',
    brand: 'Anker',
    countInStock: 90,
    rating: 4.7,
    numReviews: 3210,
    isFeatured: true,
  },
  {
    name: 'Baseus Blade 20,000mAh Laptop Power Bank',
    description: 'Ultra-slim 20,000mAh power bank with 100W USB-C PD output. 12mm thin body fits in any laptop bag. Digital display shows exact battery percentage. Charges a 16" MacBook Pro to 50% in 45 minutes.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    category: 'Power Banks',
    brand: 'Baseus',
    countInStock: 55,
    rating: 4.6,
    numReviews: 1876,
    isFeatured: false,
  },
  {
    name: 'Mophie Powerstation Pro XL 20,000mAh',
    description: 'Premium 20,000mAh wireless power bank with 15W Qi2 wireless charging pad on top. Integrated Lightning connector for iPhones. Ripple-texture rubber body with soft-touch finish.',
    price: 149.95,
    image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80',
    category: 'Power Banks',
    brand: 'Mophie',
    countInStock: 30,
    rating: 4.4,
    numReviews: 542,
    isFeatured: false,
  },

  // ─── Headphones & Audio ─────────────────────────────────────────────────────
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise cancellation with 8 microphones and Auto NC Optimizer. Up to 30 hours battery life. Precise Voice Pickup for crystal-clear calls. Multipoint connection pairs with 2 devices simultaneously.',
    price: 349.99,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80',
    category: 'Headphones & Audio',
    brand: 'Sony',
    countInStock: 48,
    rating: 4.8,
    numReviews: 5890,
    isFeatured: true,
  },
  {
    name: 'Apple AirPods Pro (2nd Gen) USB-C',
    description: 'AirPods Pro with H2 chip deliver up to 2× more Active Noise Cancellation. Adaptive Audio seamlessly blends Transparency and ANC. Up to 30 hours total listening time. Vision Pro compatible spatial audio.',
    price: 249.00,
    image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&q=80',
    category: 'Headphones & Audio',
    brand: 'Apple',
    countInStock: 75,
    rating: 4.7,
    numReviews: 8120,
    isFeatured: true,
  },
  {
    name: 'Bose QuietComfort Ultra Earbuds',
    description: 'Bose\'s best ever noise-cancelling earbuds with CustomTune technology that personalizes sound in seconds. World-class noise cancellation with Aware Mode. Up to 6 hours battery + 24 hours in the case.',
    price: 299.00,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
    category: 'Headphones & Audio',
    brand: 'Bose',
    countInStock: 36,
    rating: 4.6,
    numReviews: 2340,
    isFeatured: false,
  },
  {
    name: 'JBL Charge 5 Waterproof Bluetooth Speaker',
    description: '40W stereo sound with punchy bass from dual passive radiators. IP67 waterproof and dustproof. 20 hours playtime. Built-in power bank charges your devices. Party Boost connects multiple JBL speakers.',
    price: 179.95,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
    category: 'Headphones & Audio',
    brand: 'JBL',
    countInStock: 60,
    rating: 4.7,
    numReviews: 4200,
    isFeatured: false,
  },

  // ─── Keyboards ──────────────────────────────────────────────────────────────
  {
    name: 'Keychron Q1 Pro QMK/VIA Wireless Mechanical',
    description: 'Gasket-mounted 75% mechanical keyboard in a CNC-machined aluminum body. QMK/VIA-compatible for full programmability. Kailh Box Brown switches. Knob for volume control. Tri-mode connection: Bluetooth, 2.4GHz, USB-C.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&q=80',
    category: 'Keyboards',
    brand: 'Keychron',
    countInStock: 30,
    rating: 4.8,
    numReviews: 1540,
    isFeatured: true,
  },
  {
    name: 'Logitech MX Keys S Wireless Keyboard',
    description: 'Smart illuminated keyboard with Perfect Stroke keys for precise typing. Backlit keys auto-adjust based on ambient light. Connects up to 3 devices via Bluetooth or USB. Up to 10 days battery (5 months without backlight).',
    price: 109.99,
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=800&q=80',
    category: 'Keyboards',
    brand: 'Logitech',
    countInStock: 85,
    rating: 4.6,
    numReviews: 3780,
    isFeatured: false,
  },
  {
    name: 'Razer BlackWidow V4 Pro Mechanical',
    description: 'Full-size wireless mechanical gaming keyboard with Razer Yellow optical switches (45g actuation force). Doubleshot ABS keycaps. Magnetic wrist rest included. Chroma RGB per-key lighting.',
    price: 229.99,
    image: 'https://images.unsplash.com/photo-1595044426077-d36d9236d44a?w=800&q=80',
    category: 'Keyboards',
    brand: 'Razer',
    countInStock: 22,
    rating: 4.5,
    numReviews: 892,
    isFeatured: false,
  },
  {
    name: 'Apple Magic Keyboard with Touch ID (USB-C)',
    description: 'Slim Apple Magic Keyboard with Touch ID for secure login and Apple Pay. Scissor mechanism keys with 1mm travel. USB-C to USB-C cable included. Months of battery from a single charge.',
    price: 129.00,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    category: 'Keyboards',
    brand: 'Apple',
    countInStock: 100,
    rating: 4.7,
    numReviews: 2150,
    isFeatured: false,
  },

  // ─── Gaming Accessories ──────────────────────────────────────────────────────
  {
    name: 'Razer DeathAdder V3 HyperSpeed Gaming Mouse',
    description: 'Iconic ergonomic FPS mouse with HyperSpeed wireless at 8,000Hz polling rate. Optical Focus Pro sensor with 35,000 DPI. 90-hour battery. Ultra-lightweight at 63g. Gen-3 Razer Optical switches.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
    category: 'Gaming Accessories',
    brand: 'Razer',
    countInStock: 55,
    rating: 4.8,
    numReviews: 3420,
    isFeatured: true,
  },
  {
    name: 'SteelSeries Arctis Nova Pro Wireless Headset',
    description: 'Premium wireless gaming headset with active noise cancellation and dual-system wireless (2.4GHz + Bluetooth). Swappable battery system for infinite play. Hi-Res audio with 40mm neodymium drivers.',
    price: 349.99,
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=800&q=80',
    category: 'Gaming Accessories',
    brand: 'SteelSeries',
    countInStock: 18,
    rating: 4.7,
    numReviews: 1230,
    isFeatured: false,
  },
  {
    name: 'Xbox Elite Wireless Controller Series 2',
    description: 'Premium Xbox controller with 4 paddles, adjustable-tension thumbsticks and hair trigger locks. Up to 40 hours battery life. Rubberized grip and textured triggers. USB-C charging with cradle included.',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&q=80',
    category: 'Gaming Accessories',
    brand: 'Microsoft',
    countInStock: 40,
    rating: 4.6,
    numReviews: 5600,
    isFeatured: false,
  },
  {
    name: 'Corsair MM700 RGB Extended Gaming Mouse Pad',
    description: 'Extra-large (36" × 15") RGB gaming desk pad with 360° edge lighting and 3-zone RGB. Micro-textured surface for precise tracking. Anti-slip rubber base. USB passthrough for convenient port access.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=800&q=80',
    category: 'Gaming Accessories',
    brand: 'Corsair',
    countInStock: 70,
    rating: 4.5,
    numReviews: 1870,
    isFeatured: false,
  },

  // ─── Smart Watches ───────────────────────────────────────────────────────────
  {
    name: 'Apple Watch Series 9 (GPS + Cellular)',
    description: 'The most powerful Apple Watch with S9 chip and new Double Tap gesture. 18-hour battery, always-on Retina display, crash detection, ECG, blood oxygen monitoring. Carbon-neutral Watch option available.',
    price: 499.00,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80',
    category: 'Smart Watches',
    brand: 'Apple',
    countInStock: 50,
    rating: 4.8,
    numReviews: 7820,
    isFeatured: true,
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic 47mm',
    description: 'Premium smartwatch with iconic rotating bezel and Sapphire Crystal glass. Advanced Health with sleep coaching, body composition and continuous heart rate. 40-hour battery. BioActive Sensor for skin temperature.',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    category: 'Smart Watches',
    brand: 'Samsung',
    countInStock: 35,
    rating: 4.5,
    numReviews: 3120,
    isFeatured: false,
  },
  {
    name: 'Garmin Fenix 7 Solar Multisport GPS Watch',
    description: 'Rugged multisport GPS watch with solar charging lens for virtually unlimited battery in sunlight. Built-in maps, TopoActive maps. Advanced training metrics: VO2 max, training load, recovery time. MIL-STD-810 rated.',
    price: 699.99,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    category: 'Smart Watches',
    brand: 'Garmin',
    countInStock: 20,
    rating: 4.7,
    numReviews: 2450,
    isFeatured: false,
  },
  {
    name: 'Fitbit Charge 6 Advanced Fitness Tracker',
    description: 'Health and fitness tracker with built-in Google Maps and Google Wallet. ECG app, 24/7 heart rate, SpO2. Compatible with YouTube Music and Google apps. 7-day battery. Works with Android and iOS.',
    price: 159.95,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80',
    category: 'Smart Watches',
    brand: 'Fitbit',
    countInStock: 80,
    rating: 4.4,
    numReviews: 4320,
    isFeatured: false,
  },

  // ─── PC Accessories ──────────────────────────────────────────────────────────
  {
    name: 'LG 27UK850-W 27" 4K USB-C Monitor',
    description: '27-inch 4K IPS display with 98% DCI-P3 wide color gamut and 60W USB-C Power Delivery. Two HDMI 2.0 ports, DisplayPort 1.4. Built-in speakers. VESA HDR400 certified. Height-adjustable stand with pivot.',
    price: 649.99,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a573d5f5ea?w=800&q=80',
    category: 'PC Accessories',
    brand: 'LG',
    countInStock: 15,
    rating: 4.6,
    numReviews: 1980,
    isFeatured: true,
  },
  {
    name: 'Logitech C920s Pro HD Webcam',
    description: '1080p/30fps Full HD webcam with automatic light correction and privacy shutter. Dual stereo microphones with noise reduction. Full HD 78° diagonal field of view. Works with Zoom, Teams and Google Meet.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1587302186428-d1f07b65abc9?w=800&q=80',
    category: 'PC Accessories',
    brand: 'Logitech',
    countInStock: 95,
    rating: 4.5,
    numReviews: 6730,
    isFeatured: false,
  },
  {
    name: 'Anker 655 USB-C Hub (8-in-1)',
    description: '8-in-1 USB-C hub with 4K HDMI, 100W Power Delivery passthrough, 2× USB-A 5Gbps, USB-C 5Gbps, microSD/SD card slots. Aluminum body with a braided cable. Plug-and-play — no drivers needed.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1625948515291-2a12a94ebdde?w=800&q=80',
    category: 'PC Accessories',
    brand: 'Anker',
    countInStock: 150,
    rating: 4.7,
    numReviews: 4120,
    isFeatured: false,
  },
  {
    name: 'Elgato Stream Deck MK.2',
    description: '15 customizable LCD keys for instant control of streaming, editing and more. Works with OBS, Twitch, Spotify and 300+ apps. Detachable USB-C cable. Tiltable stand with interchangeable face plates.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    category: 'PC Accessories',
    brand: 'Elgato',
    countInStock: 42,
    rating: 4.8,
    numReviews: 3890,
    isFeatured: false,
  },
  {
    name: 'Logitech MX Master 3S Wireless Mouse',
    description: 'Ergonomic productivity mouse with MagSpeed electromagnetic scroll wheel that scrolls 1,000 lines per second. 8K DPI sensor works on any surface including glass. Multi-device connectivity for up to 3 computers. Silent clicks.',
    price: 99.99,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=800&q=80',
    category: 'PC Accessories',
    brand: 'Logitech',
    countInStock: 110,
    rating: 4.8,
    numReviews: 9240,
    isFeatured: true,
  },

  // ─── Networking ──────────────────────────────────────────────────────────────
  {
    name: 'TP-Link Archer AXE300 Wi-Fi 6E Tri-Band Router',
    description: 'Wi-Fi 6E tri-band router delivering combined 19,000 Mbps across 6GHz (5,764 Mbps), 5GHz (4,804 Mbps) and 2.4GHz (1,147 Mbps) bands. 8 high-gain antennas, 2.5GbE WAN port. Ideal for 100+ devices.',
    price: 349.99,
    image: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&q=80',
    category: 'Networking',
    brand: 'TP-Link',
    countInStock: 28,
    rating: 4.6,
    numReviews: 1340,
    isFeatured: false,
  },
  {
    name: 'Eero Pro 6E Mesh Wi-Fi System (3-Pack)',
    description: 'True tri-band mesh system with dedicated 6GHz backhaul. Covers up to 6,000 sq ft with speeds up to 2.3 Gbps. Smart home controls, automatic updates, and optional Eero Secure subscription.',
    price: 499.00,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    category: 'Networking',
    brand: 'Amazon',
    countInStock: 20,
    rating: 4.5,
    numReviews: 980,
    isFeatured: false,
  },
];

const importData = async () => {
  try {
    await connectDB();

    await Category.deleteMany();
    await Category.insertMany(categories);
    console.log(`✓ ${categories.length} categories seeded`);

    await Product.deleteMany();
    await Product.insertMany(sampleProducts);
    console.log(`✓ ${sampleProducts.length} electronics products seeded`);

    process.exit(0);
  } catch (error) {
    console.error(`Seeder failed: ${error.message}`);
    process.exit(1);
  }
};

importData();
